name: Simple Go Pipeline - validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow:
    uses: baalimago/simple-go-pipeline/.github/workflows/validate.yml@v0.2.7
    with:
      go-version: '1.22'
